version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql


  app:
    build: ./app
    image: lucasribeirodesouza2000/proxy-nginx-fullcycle:latest
    container_name: node_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fullcycle
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data:
